### PR TITLE
A more portable way to handle long running scripts

### PR DESCRIPTION
**Pull request by larshesel**
I think this should work on all platforms... @codeadict would you be able to test this on OSX?

### CODE REVIEW

**Comment by codeadict** [comment]
The -s works on OSX, i'm testing now with VerneMQ

**Comment by codeadict** [comment]
Tested using your branch of `node_package`, works perfect, i can do some testing on FreeBSD and Fedora over the weekend

**Review by codeadict — APPROVED** [review]

**Comment by larshesel** [comment]
Great - let's go with this for the moment then.

**Comment by codeadict** [comment]
Hey @larshesel , I tested this in both Fedora and FreeBSD and worked like a charm

**Comment by larshesel** [comment]
Awesome, thanks!

**Comment by larshesel** [comment]
Awesome, thanks!

**Pull request merged**
